name: CI github actions
on:
    push:
jobs:
    test:
        runs-on: ubuntu-lastest

        steps:
            - uses: actions/checkout@v4
            - name: Hello world
              run: echo "Heloo world"
            - name: Listar archivos
              run: ls -lha
