name: CI github actions
on:
    push:
        branches: [main]
jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Hello world
              run: echo "Heloo world"
            - name: Listar archivos
              run: ls -lha
